### PR TITLE
Renaming calc_rise and calc_set to rise_time and set_time

### PR DESCRIPTION
**Pull request by bmorris3**
Because I want to pick a fight with my past self.

### CODE REVIEW

**Comment by cdeil** [comment]
:+1: 
(I think it's good to have the word "time" in this method, because it returns a time.)

@astroplanners/astroplanners-contributors Please comment if this change is OK with you.

**Comment by bmorris3** [comment]
Vote between: `rise_time`, `target_rise_time`, `rising_time`.

**Comment by ejeschke** [comment]
I vote for rising_time, setting_time

**Comment by adrn** [comment]
`target_set_time` / `target_rise_time`

**Comment by cdeil** [comment]
target_set_time / target_rise_time

**Comment by bmorris3** [comment]
I vote `rise_time`, `set_time`.

**Comment by eteq** [comment]
I vote `rising_time`/`setting_time`

**Comment by bmorris3** [comment]
@adrn votes `target_set_time`

**Comment by cdeil** [comment]
Note that we already have `moonrise`, `sunrise`, `moonset`, `sunset`.
Don't know if this favours one of the proposed names.

**Comment by jberlanga** [comment]
target_set_time / target_rise_time

(although I still like target_set/targetset, etc.)

**Comment by eteq** [comment]
By my count `target_*_time` is the winner, right?

**Comment by bmorris3** [comment]
@astroplanners/astroplanners-contributors After some more discussion on Slack, I've updated the methods to have the most self-consistent names possible in the latest commit (13931c8). Here's the scheme:

| old name | new name |
|--------------|---------------|
| sunrise    | sun_rise   |
| moonrise    | moon_rise  |
| calc_rise | target_rise | 
| calc_meridian_transit | target_meridian_transit |

**Comment by cdeil** [comment]
Thanks.
I'm still +1 on adding `_time` everywhere.

It's not 100% obvious from the name what `sun_rise` is? A time? An azimuth location? A `SunRise` object?

@bmorris3 – Note that it's obvious to you what these methods do and you've been typing these names a lot, so you prefer short names. But the vast majority of users will use this package sporadically, maybe every few weeks or months, and I think will prefer more explicit names, even if it means typing or reading an extra `_time` here and there.

Maybe let's do another vote and then merge?
Are these options enough or does someone strongly prefer something else?
Option A: merge as-is.
Option B: add `_time` to these methods.

**Comment by eteq** [comment]
:+1: to @cdeil's suggestion of the A/B vote (@jberlanga @ejeschke @adrn ?)

I vote A - I think the fact that it's a time will nearly always be from the context.

But so as to make things easier: I see @cdeil's point that that might be because I'm too deep in already.  So if it's a tie (3 votes A and 3 votes B), I change my vote to B .

**Comment by adrn** [comment]
B

**Comment by jberlanga** [comment]
B

**Comment by bmorris3** [comment]
I'm calling the votes settled in favor of B. 

| old name | new name |
|--------------|---------------|
| sunrise    | sun_rise_time   |
| moonrise    | moon_rise_time  |
| calc_rise | target_rise_time | 
| calc_meridian_transit | target_meridian_transit_time |

**Comment by cdeil** [comment]
@bmorris3 – Thanks for compromising on this naming question.

Travis-ci passed. Ready to merge, right?

**Comment by bmorris3** [comment]
Of course! And yes. @jberlanga – heads up on the new names!

**Pull request merged**
